import json
import os
import re
import sys
from pathlib import Path

import numpy as np
import pytest
from ase.spacegroup import crystal

from symmetrix.metal_codegen import (
    metal_m0_metadata,
    metal_r1_metadata,
    render_jit_m0_metal_source,
    render_jit_r1_metal_source,
)

FIXTURE_CONTRACT = (
    Path(__file__).resolve().parent
    / "data"
    / "jit_r1_fixture_c4_e3_l0_contract.json.in"
)
M0_CONTRACT = (
    Path(__file__).resolve().parent
    / "data"
    / "execution_contracts"
    / "standard_m0_contract.json"
)
OMAT_CONTRACT = (
    Path(__file__).resolve().parent
    / "data"
    / "execution_contracts"
    / "jit_r1_mace_off23_small_contract.json"
)


@pytest.mark.parametrize("contract_path", [FIXTURE_CONTRACT, OMAT_CONTRACT])
def test_metal_r1_source_is_fp32_msl_with_edge_kernels(contract_path):
    contract = json.loads(contract_path.read_text())
    source = render_jit_r1_metal_source(contract)
    metadata = metal_r1_metadata(contract)

    assert source.startswith("// Generated by symmetrix.metal_codegen")
    assert metadata["contract_fingerprint"] in source
    for kernel in ("symmetrix_r1_forward", "symmetrix_r1_source", "symmetrix_r1_edge"):
        assert f"kernel void {kernel}(" in source
    assert not re.search(r"\bdouble\b|\bstd::|\bnullptr\b|if constexpr", source)
    assert "simd_sum(local_force_x)" in source
    assert "channel += 32" in source
    blocked = "kernel void symmetrix_r1_edge_blocked(" in source
    assert blocked == (metadata["channels"] % 32 == 0)
    if blocked:
        assert "const int channel = block_base + int(lane);" in source
        assert "forces[coordinate_offset] -= local_force_x;" in source


def test_metal_m0_source_covers_every_term():
    contract = json.loads(M0_CONTRACT.read_text())
    metadata = metal_m0_metadata(contract)
    source = render_jit_m0_metal_source(contract)

    assert source.count("out[") - 2 >= metadata["term_count"]
    assert "kernel void symmetrix_m0_forward(" in source
    assert "kernel void symmetrix_m0_reverse(" in source
    assert "simd_sum(scale)" in source
    assert not re.search(r"\bdouble\b|\bstd::", source)


def test_metal_r1_metadata_matches_host_plugin_shape():
    contract = json.loads(FIXTURE_CONTRACT.read_text())
    metadata = metal_r1_metadata(contract)

    assert metadata["abi_version"] == 1
    assert metadata["channels"] > 0
    assert metadata["edge_harmonics"] in (1, 4, 9, 16)
    assert metadata["source_harmonics"] in (1, 4, 9, 16)
    assert metadata["output_components"] > 0


def test_metal_requires_float32(tmp_path):
    from symmetrix import Symmetrix

    with pytest.raises(ValueError, match="Metal has no FP64"):
        Symmetrix(tmp_path / "unused.json", dtype="float64", metal=True)


def _metal_extension_available():
    if sys.platform != "darwin":
        return False, "Metal requires macOS"
    try:
        native = __import__("symmetrix.symmetrix", fromlist=["MACEKokkosFloat"])
    except ImportError as error:
        return False, f"native extension unavailable: {error}"
    evaluator = getattr(native, "MACEKokkosFloat", None)
    if evaluator is None or not hasattr(evaluator, "_load_metal_r1_module"):
        return False, "the native extension was built without SYMMETRIX_METAL"
    return True, ""


@pytest.fixture(scope="module")
def omat_small_model():
    available, reason = _metal_extension_available()
    if not available:
        pytest.skip(reason)
    foundations = pytest.importorskip(
        "mace.calculators.foundations_models",
        reason="mace-torch is required to download the foundation model",
    )
    from model_downloads import test_model_cache_dir

    cache_dir = test_model_cache_dir() / "mace-foundation"
    cache_dir.mkdir(parents=True, exist_ok=True)
    previous = os.environ.get("XDG_CACHE_HOME")
    os.environ["XDG_CACHE_HOME"] = str(cache_dir)
    try:
        return str(foundations.download_mace_mp_checkpoint("small-omat-0"))
    except Exception as exc:
        pytest.skip(f"MACE foundation model is not available: {exc}")
    finally:
        if previous is None:
            del os.environ["XDG_CACHE_HOME"]
        else:
            os.environ["XDG_CACHE_HOME"] = previous


def _strontium_titanate():
    a = 3.905
    atoms = crystal(
        ["Sr", "Ti", "O"],
        basis=[(0, 0, 0), (0.5, 0.5, 0.5), (0.5, 0.5, 0)],
        spacegroup=221,
        cellpar=[a, a, a, 90, 90, 90],
    ).repeat((2, 2, 2))
    atoms.rattle(stdev=0.05, seed=3)
    return atoms


def _evaluate(atoms, calc):
    atoms = atoms.copy()
    atoms.calc = calc
    return atoms.get_potential_energy(), atoms.get_forces(), atoms.get_stress()


def test_metal_m0_r0_r1_match_host_fp32_and_run_on_gpu(omat_small_model):
    from symmetrix import Symmetrix

    species = [8, 22, 38]
    host = Symmetrix(omat_small_model, species=species, dtype="float32")
    metal = Symmetrix(omat_small_model, species=species, dtype="float32", metal=True)
    atoms = _strontium_titanate()

    e_host, f_host, s_host = _evaluate(atoms, host)
    e_metal, f_metal, s_metal = _evaluate(atoms, metal)

    assert metal.metal_status == "ready"
    assert metal.metal_device
    statistics = metal.metal_statistics()
    assert statistics["forward_launches"] >= 1
    assert statistics["reverse_launches"] >= 1
    assert statistics["gpu_seconds"] > 0.0
    assert statistics["r0_forward_launches"] >= 1
    assert statistics["r0_reverse_launches"] >= 1
    assert statistics["r0_gpu_seconds"] > 0.0
    assert statistics["m0_forward_launches"] >= 1
    assert statistics["m0_reverse_launches"] >= 1
    assert statistics["m1_forward_launches"] >= 1
    assert statistics["m1_reverse_launches"] >= 1
    assert statistics["a1_forward_launches"] >= 1
    assert statistics["a1_reverse_launches"] >= 1
    # dPhi1 produced by the A1 reverse is consumed on the GPU by R1.
    assert statistics["resident_uploads_skipped"] >= 1
    # The evaluator's edge list is receiver-ordered, so the channel-blocked
    # edge kernel runs.
    assert statistics["blocked_edge_launches"] >= 1
    assert host.metal_status == "disabled"
    # FP32 summation order differs between the host owners and the GPU.
    assert abs(e_metal - e_host) / len(atoms) < 1e-5
    np.testing.assert_allclose(f_metal, f_host, atol=1e-4)
    np.testing.assert_allclose(s_metal, s_host, atol=1e-5)
